force-app/main/default/objects/Vechile__c/Vechile__c.object-meta.xml
<CustomObject>
    <description>Holds the information about the vehicle</description>
    <label>Vechile</label>
    <nameField>
        <label>Vechile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vechiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vechile__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Color</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vechile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vechiles</relationshipLabel>
    <relationshipName>Vechiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vechile__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vechile__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/VechileMaintenance_Test.cls
@isTest(SeeAllData=false)
public class VechileMaintenance_Test {
	static testMethod void VechileMaintenanceTest() {
        Account acc = new account();
        acc.name = 'test acc';
        insert acc;
        
        Account acc1 = new account();
        acc1.name = 'test acc';
        insert acc1;
        
        contact con = new contact();
        con.lastname = 'con last';
        con.email='testcon@mailinator.com';
        con.accountId = acc.id;
        insert con;
        
        contact con1 = new contact();
        con1.lastname = 'con1 last';
        con1.email='testcon1@mailinator.com';
        con1.accountId = acc1.id;
        insert con1;
        
        list<Vechile__c> vechileList = new list<Vechile__c>();
        Vechile__c v = new Vechile__c();
        v.name = 'Vechile Test';
        v.Model__c = 'BMW x5';
        v.contact__c = con.id;
        v.Make__c='us';
        v.Year__c = date.today();
        v.Colour__c = 'white';
        v.Last_Service_Date__c = date.today();
        insert v;
        
        v.Odometer_Reading__c = 9500;
        update v;
        
        vechileList.add(v);
      
            
    }
}