force-app/main/default/objects/Maintenance_Request__c/Maintenance_Request__c.object-meta.xml
<CustomObject>
    <description>Request for doing the maintenanceservice</description>
    <label>Maintenance Request</label>
    <nameField>
        <label>Maintenance Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Maintenance Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Maintenance_Request__c/fields/Maintenance_Date__c.field-meta.xml
<CustomField>
    <fullName>Maintenance_Date__c</fullName>
    <label>Maintenance Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Confirmed</fullName>
            </value>
            <value>
                <fullName>Confirmed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Maintenance_Request__c/fields/Vechile__c.field-meta.xml
<CustomField>
    <fullName>Vechile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vechile</label>
    <referenceTo>Vechile__c</referenceTo>
    <relationshipLabel>Maintenance Requests</relationshipLabel>
    <relationshipName>Maintenance_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vechile__c/Vechile__c.object-meta.xml
<CustomObject>
    <description>Holds the information about the vehicle</description>
    <label>Vechile</label>
    <nameField>
        <label>Vechile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vechiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Vechile__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vechiles</relationshipLabel>
    <relationshipName>Vechiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vechile__c/fields/Next_Service_Date__c.field-meta.xml
<CustomField>
    <fullName>Next_Service_Date__c</fullName>
    <formula>ADDMONTHS(Last_Service_Date__c,11)</formula>
    <label>Next Service Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateMaintenceRequestRec.cls
public class CreateMaintenceRequestRec {
    public static void createMaintenceRec(list<Vechile__c> vechileList){
        list<Maintenance_Request__c> insertMRList = new list<Maintenance_Request__c>();
        set<id> conIds = new set<id>();
        for(Vechile__c v : vechileList){
            if(v.contact__c!=null)
                conIds.add(v.contact__c);
        }
        //map to get email id of respective contact
        Map<ID, contact> conToEmail = new Map<ID, contact>([SELECT Id, Name,email,lastname FROM contact where id In:conIds]);
        //creation of Maintenance records
        for(Vechile__c v : vechileList){
            system.debug('___test class exception+____'+v);
            Maintenance_Request__c mrRec = new Maintenance_Request__c(name=v.name+' '+ conToEmail.get(v.contact__c).lastName + ' Request', 
                                                                      Maintenance_Date__c = v.Next_Service_Date__c,
                                                                      Status__c = 'Not Confirmed',
                                                                      Odometer_Reading__c = v.Odometer_Reading__c,
                                                                      Vechile__c = v.id,
                                                                      Customer_Email__c = conToEmail.get(v.contact__c).Email);
            insertMRList.add(mrRec);
        }
        if(insertMRList.size()>0)
            insert insertMRList;
        
    }
}